import Foundation

// MARK: - Calisthenics Difficulty
// User-selectable difficulty level that determines which exercise pool is used.

enum CalisthenicsDifficulty: String, CaseIterable {
    case easy = "Easy"
    case medium = "Medium"
    case hard = "Hard"

    var emoji: String {
        switch self {
        case .easy: return "🟢"
        case .medium: return "🟡"
        case .hard: return "🔴"
        }
    }
}

// MARK: - MessageBank
// Loads and serves reminder messages from MessageBank.json.
//
// Features:
// - Loads all messages from a bundled JSON file
// - Random selection within category + tier
// - No immediate repeats (tracks what was last shown per category)
// - For calisthenics, fills in {exercise} placeholders with cycling exercises
// - Exercises are grouped by difficulty level (Easy/Medium/Hard)

class MessageBank {
    static let shared = MessageBank()

    // The full message bank: [categoryKey: [tierKey: [messages]]]
    private var messages: [String: [String: [String]]] = [:]

    // Tracks the last message shown per category to avoid immediate repeats
    private var lastShown: [String: String] = [:]

    // MARK: - Calisthenics exercise pools by difficulty
    private let exercisesByDifficulty: [CalisthenicsDifficulty: [String]] = [
        .easy: [
            "10 wall pushups",
            "10 chair-assisted squats",
            "15 calf raises",
            "a 15-second desk stretch (arms overhead)",
            "10 seated leg raises",
            "10 shoulder rolls (each direction)",
            "a 20-second standing side stretch (each side)",
        ],
        .medium: [
            "5-10 pushups",
            "10-15 squats",
            "10-15 lunges (each leg)",
            "a 20-30 second plank",
            "15-20 calf raises",
            "10 tricep dips (use your chair)",
            "20 jumping jacks",
        ],
        .hard: [
            "10 burpees",
            "15 mountain climbers (each side)",
            "10 jump squats",
            "10 diamond pushups",
            "a 45-second plank",
            "10 pike pushups",
            "15 tuck jumps",
        ],
    ]

    // Tier 3 adds one extra "punishment" exercise per difficulty
    private let tier3BonusExercise: [CalisthenicsDifficulty: String] = [
        .easy: "20 wall pushups FAST (no slacking!)",
        .medium: "10 BURPEES (yes, really)",
        .hard: "15 BURPEE-TO-TUCK-JUMPS (suffer beautifully)",
    ]

    // MARK: - Exercise cycling index (persisted across launches)
    private var exerciseIndex: Int {
        get { UserDefaults.standard.integer(forKey: "calisthenicsExerciseIndex") }
        set { UserDefaults.standard.set(newValue, forKey: "calisthenicsExerciseIndex") }
    }

    private var lastDifficulty: String {
        get { UserDefaults.standard.string(forKey: "calisthenicsLastDifficulty") ?? "Medium" }
        set { UserDefaults.standard.set(newValue, forKey: "calisthenicsLastDifficulty") }
    }

    // MARK: - Initialization

    private init() {
        loadMessages()
    }

    // MARK: - Load messages from JSON

    private func loadMessages() {
        // Try to find MessageBank.json in the SPM resource bundle
        // Bundle.module is auto-generated by Swift Package Manager
        guard let url = Bundle.module.url(forResource: "MessageBank", withExtension: "json") else {
            print("⚠️ MessageBank.json not found in bundle — using fallback messages")
            loadFallbackMessages()
            return
        }

        do {
            let data = try Data(contentsOf: url)
            if let json = try JSONSerialization.jsonObject(with: data) as? [String: [String: [String]]] {
                messages = json
                print("✅ MessageBank loaded: \(countMessages()) messages across \(messages.count) categories")
            }
        } catch {
            print("⚠️ Failed to parse MessageBank.json: \(error) — using fallback messages")
            loadFallbackMessages()
        }
    }

    /// Count total messages for logging
    private func countMessages() -> Int {
        var count = 0
        for (_, tiers) in messages {
            for (_, msgs) in tiers {
                count += msgs.count
            }
        }
        return count
    }

    // MARK: - Get a random message

    /// Returns a random message for the given category and tier.
    /// Avoids repeating the last message shown for that category.
    /// For calisthenics, fills in the {exercise} placeholder.
    func getMessage(for category: ReminderCategory, tier: EscalationTier) -> String {
        let categoryKey = jsonKey(for: category)
        let tierKey = jsonKey(for: tier)

        guard let tierMessages = messages[categoryKey]?[tierKey],
              !tierMessages.isEmpty else {
            // Fallback if something went wrong
            return "Time for a \(category.rawValue.lowercased()) break!"
        }

        // Pick a random message that isn't the same as the last one shown
        var message: String
        let lastMessage = lastShown[categoryKey]

        if tierMessages.count == 1 {
            // Only one message available — no choice
            message = tierMessages[0]
        } else {
            // Keep picking until we get something different from last time
            repeat {
                message = tierMessages.randomElement()!
            } while message == lastMessage
        }

        // Track what we showed
        lastShown[categoryKey] = message

        // For calisthenics, replace {exercise} placeholder with the next exercise in the cycle
        if category == .calisthenics {
            let difficulty = currentDifficulty()

            // Reset cycle if difficulty changed
            if difficulty.rawValue != lastDifficulty {
                exerciseIndex = 0
                lastDifficulty = difficulty.rawValue
            }

            var exercisePool = exercisesByDifficulty[difficulty] ?? exercisesByDifficulty[.medium]!
            if tier == .unhingedGremlin, let bonus = tier3BonusExercise[difficulty] {
                exercisePool.append(bonus)
            }

            // Cycle through exercises sequentially
            let index = exerciseIndex % exercisePool.count
            let exercise = exercisePool[index]
            exerciseIndex += 1

            message = message.replacingOccurrences(of: "{exercise}", with: exercise)
        }

        return message
    }

    // MARK: - JSON key mapping

    /// Maps ReminderCategory to the key used in MessageBank.json
    private func jsonKey(for category: ReminderCategory) -> String {
        switch category {
        case .standSit: return "standSit"
        case .water: return "water"
        case .walk: return "walk"
        case .dance: return "dance"
        case .calisthenics: return "calisthenics"
        }
    }

    /// Maps EscalationTier to the key used in MessageBank.json
    private func jsonKey(for tier: EscalationTier) -> String {
        switch tier {
        case .jarvis: return "jarvis"
        case .concernedJarvis: return "concernedJarvis"
        case .unhingedGremlin: return "unhingedGremlin"
        }
    }

    // MARK: - Difficulty helper

    /// Reads the current calisthenics difficulty from UserDefaults
    private func currentDifficulty() -> CalisthenicsDifficulty {
        let raw = UserDefaults.standard.string(forKey: "calisthenicsDifficulty") ?? "Medium"
        return CalisthenicsDifficulty(rawValue: raw) ?? .medium
    }

    // MARK: - Fallback messages (if JSON fails to load)

    private func loadFallbackMessages() {
        messages = [
            "water": [
                "jarvis": ["Might I suggest hydration? Your cells have been remarkably patient."],
                "concernedJarvis": ["I've now asked twice about the water situation. This is becoming a pattern."],
                "unhingedGremlin": ["DRINK WATER OR I WILL HAUNT YOUR DESKTOP FOREVER. I LIVE HERE NOW."]
            ],
            "standSit": [
                "jarvis": ["Time to change altitude. Your spine would appreciate the variety."],
                "concernedJarvis": ["Your spine has begun drafting a resignation letter."],
                "unhingedGremlin": ["STAND UP RIGHT NOW. I WILL WIGGLE. YOU DO NOT WANT ME TO WIGGLE."]
            ],
            "walk": [
                "jarvis": ["A brief constitutional is in order."],
                "concernedJarvis": ["Your legs are wondering if they've been discontinued."],
                "unhingedGremlin": ["WALK. MOVE. LOCOMOTE. JUST ACTIVATE THOSE LIMBS."]
            ],
            "dance": [
                "jarvis": ["Perhaps a shimmy? No one is watching. Except me."],
                "concernedJarvis": ["The dance break is becoming less optional."],
                "unhingedGremlin": ["DANCE BREAK. THIS IS MANDATORY. MOVE IT."]
            ],
            "calisthenics": [
                "jarvis": ["{exercise}, if you please."],
                "concernedJarvis": ["{exercise}. Your muscles are sending distress signals."],
                "unhingedGremlin": ["{exercise}. RIGHT NOW. THIS IS YOUR FINAL WARNING."]
            ]
        ]
    }
}
