import Foundation

// MARK: - MessageBank
// Loads and serves reminder messages from MessageBank.json.
//
// Features:
// - Loads all messages from a bundled JSON file
// - Random selection within category + tier
// - No immediate repeats (tracks what was last shown per category)
// - For calisthenics, fills in {exercise} placeholders with random exercises

class MessageBank {
    static let shared = MessageBank()

    // The full message bank: [categoryKey: [tierKey: [messages]]]
    private var messages: [String: [String: [String]]] = [:]

    // Tracks the last message shown per category to avoid immediate repeats
    private var lastShown: [String: String] = [:]

    // MARK: - Calisthenics exercise pool
    // Each entry is a string that can replace {exercise} in calisthenics messages
    private let exercises: [String] = [
        "5-10 pushups",
        "10-15 squats",
        "10-15 lunges (each leg)",
        "a 20-30 second plank",
        "15-20 calf raises",
        "10 tricep dips (use your chair)",
        "20 jumping jacks",
    ]

    // Tier 3 gets burpees as "punishment" (per the spec!)
    private let tier3Exercises: [String] = [
        "5-10 pushups",
        "10-15 squats",
        "10-15 lunges (each leg)",
        "a 20-30 second plank",
        "10 BURPEES (yes, really)",
        "15-20 calf raises",
        "10 tricep dips (use your chair)",
        "20 jumping jacks",
    ]

    // MARK: - Initialization

    private init() {
        loadMessages()
    }

    // MARK: - Load messages from JSON

    private func loadMessages() {
        // Try to find MessageBank.json in the SPM resource bundle
        // Bundle.module is auto-generated by Swift Package Manager
        guard let url = Bundle.module.url(forResource: "MessageBank", withExtension: "json") else {
            print("⚠️ MessageBank.json not found in bundle — using fallback messages")
            loadFallbackMessages()
            return
        }

        do {
            let data = try Data(contentsOf: url)
            if let json = try JSONSerialization.jsonObject(with: data) as? [String: [String: [String]]] {
                messages = json
                print("✅ MessageBank loaded: \(countMessages()) messages across \(messages.count) categories")
            }
        } catch {
            print("⚠️ Failed to parse MessageBank.json: \(error) — using fallback messages")
            loadFallbackMessages()
        }
    }

    /// Count total messages for logging
    private func countMessages() -> Int {
        var count = 0
        for (_, tiers) in messages {
            for (_, msgs) in tiers {
                count += msgs.count
            }
        }
        return count
    }

    // MARK: - Get a random message

    /// Returns a random message for the given category and tier.
    /// Avoids repeating the last message shown for that category.
    /// For calisthenics, fills in the {exercise} placeholder.
    func getMessage(for category: ReminderCategory, tier: EscalationTier) -> String {
        let categoryKey = jsonKey(for: category)
        let tierKey = jsonKey(for: tier)

        guard let tierMessages = messages[categoryKey]?[tierKey],
              !tierMessages.isEmpty else {
            // Fallback if something went wrong
            return "Time for a \(category.rawValue.lowercased()) break!"
        }

        // Pick a random message that isn't the same as the last one shown
        var message: String
        let lastMessage = lastShown[categoryKey]

        if tierMessages.count == 1 {
            // Only one message available — no choice
            message = tierMessages[0]
        } else {
            // Keep picking until we get something different from last time
            repeat {
                message = tierMessages.randomElement()!
            } while message == lastMessage
        }

        // Track what we showed
        lastShown[categoryKey] = message

        // For calisthenics, replace {exercise} placeholder with a random exercise
        if category == .calisthenics {
            let exercisePool = (tier == .unhingedGremlin) ? tier3Exercises : exercises
            let exercise = exercisePool.randomElement()!
            message = message.replacingOccurrences(of: "{exercise}", with: exercise)
        }

        return message
    }

    // MARK: - JSON key mapping

    /// Maps ReminderCategory to the key used in MessageBank.json
    private func jsonKey(for category: ReminderCategory) -> String {
        switch category {
        case .standSit: return "standSit"
        case .water: return "water"
        case .walk: return "walk"
        case .dance: return "dance"
        case .calisthenics: return "calisthenics"
        }
    }

    /// Maps EscalationTier to the key used in MessageBank.json
    private func jsonKey(for tier: EscalationTier) -> String {
        switch tier {
        case .jarvis: return "jarvis"
        case .concernedJarvis: return "concernedJarvis"
        case .unhingedGremlin: return "unhingedGremlin"
        }
    }

    // MARK: - Fallback messages (if JSON fails to load)

    private func loadFallbackMessages() {
        messages = [
            "water": [
                "jarvis": ["Might I suggest hydration? Your cells have been remarkably patient."],
                "concernedJarvis": ["I've now asked twice about the water situation. This is becoming a pattern."],
                "unhingedGremlin": ["DRINK WATER OR I WILL HAUNT YOUR DESKTOP FOREVER. I LIVE HERE NOW."]
            ],
            "standSit": [
                "jarvis": ["Time to change altitude. Your spine would appreciate the variety."],
                "concernedJarvis": ["Your spine has begun drafting a resignation letter."],
                "unhingedGremlin": ["STAND UP RIGHT NOW. I WILL WIGGLE. YOU DO NOT WANT ME TO WIGGLE."]
            ],
            "walk": [
                "jarvis": ["A brief constitutional is in order."],
                "concernedJarvis": ["Your legs are wondering if they've been discontinued."],
                "unhingedGremlin": ["WALK. MOVE. LOCOMOTE. JUST ACTIVATE THOSE LIMBS."]
            ],
            "dance": [
                "jarvis": ["Perhaps a shimmy? No one is watching. Except me."],
                "concernedJarvis": ["The dance break is becoming less optional."],
                "unhingedGremlin": ["DANCE BREAK. THIS IS MANDATORY. MOVE IT."]
            ],
            "calisthenics": [
                "jarvis": ["{exercise}, if you please."],
                "concernedJarvis": ["{exercise}. Your muscles are sending distress signals."],
                "unhingedGremlin": ["{exercise}. RIGHT NOW. THIS IS YOUR FINAL WARNING."]
            ]
        ]
    }
}
